{% set name = "pyScope" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/WWGolay/pyScope/archive/v{{ version }}.tar.gz
  sha256: 035714292d1463744fc6e30204b71232a7e89e6dc6fc4c892ded78d63bef42d2

build:
  entry_points:
    - init-telrun-dir = pyscope.telrun:init_telrun_dir_cli
    - init-remote-dir = pyscope.telrun:init_remote_dir_cli
    - schedtel = pyscope.telrun:schedtel_cli
    - plot-schedule-gantt = pyscope.telrun:plot_schedule_gantt_cli
    - start-telrun = pyscope.telrun:start_telrun_cli
    - start-syncfiles = pyscope.telrun:start_syncfiles_cli
    - syncfiles = pyscope.telrun:syncfiles_cli
    - calc-zmag = pyscope.analysis:calc_zmag_cli
    - collect-calibration-set = pyscope.observatory:collect_calibration_set_cli
    - avg-fits = pyscope.reduction:avg_fits_cli
    - calib-images = pyscope.reduction:calib_images_cli
    - ccd-calib = pyscope.reduction:ccd_calib_cli
    - fitslist = pyscope.reduction:fitslist_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=42.0
    - wheel
    - pip
  run:
    - python >=3.10
    - astropy >=5.3.1
    - astroquery >=0.4.6
    - astroscrappy >=1.1.0
    - astroplan >=0.8
    - click >=8.1.6
    - numpy >=1.24.4
    - numpydoc >=1.5.0
    - paramiko >=3.3.1
    - photutils >=1.7.0
    - matplotlib-base >=3.5.1
    - smplotlib >=0.0.6
    - cmcrameri >=1.4.0
    - timezonefinder >=6.0.2
    - tksheet >=6.2.3
    - tqdm >=4.66.1
    - astropy-sphinx-theme >=1.1.0
    - pydata-sphinx-theme >=0.8.1
    - sphinx >=4.5.0
    - sphinx-astropy >=1.9.1
    - sphinx-copybutton >=0.5.0
    - sphinx-gallery >=0.13.0
    - prettytable >=3.8.0

test:
  imports:
    - pyscope
  commands:
    - pip check
    - init-telrun-dir --help
    - init-remote-dir --help
    - schedtel --help
    - plot-schedule-gantt --help
    - start-telrun --help
    - start-syncfiles --help
    - syncfiles --help
    - calc-zmag --help
    - collect-calibration-set --help
    - avg-fits --help
    - calib-images --help
    - ccd-calib --help
    - fitslist --help
  requires:
    - pip

about:
  home: https://github.com/WWGolay/pyScope
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wgolay30
